version: '3.9'

networks:
  jenkins_network:
    external: true

services:
  jenkins:
    # image: marine1232/jenkins_image:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Jenkins
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - jenkins_network

volumes:
  jenkins_home:
