name: Build and Deploy Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Jenkins
        run: |
          docker-compose -f docker-compose.jenkins.yml build
          docker tag <image_name>:latest ${{ secrets.DOCKER_USERNAME }}/<image_name>:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/<image_name>:latest
